import { SignInButton, useUser } from "@clerk/nextjs";
import Head from "next/head";

import { api } from "~/utils/api";

function CreatePostWizard() {
  const { user } = useUser();

  if (!user) return null;

  return (
    <div className="flex gap-3 ">
      <img
        src={user.imageUrl}
        alt="Profile Image"
        className="h-16 w-16 rounded-full"
      />
      <input
        type="text"
        className="grow bg-transparent outline-none"
        placeholder="Type some emojis to tweet"
      />
    </div>
  );
}

export default function Home() {
  const { isSignedIn, user } = useUser();

  const { data, isLoading } = api.posts.getAll.useQuery();

  console.log(data);

  if (isLoading) return <div>Loading data...</div>;

  if (!data) return <div>Sorry something went wrong!</div>;

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen justify-center">
        <div className="w-full border-x border-slate-400 md:max-w-2xl">
          <div className=" w-full  border-b border-slate-400 p-4">
            {!isSignedIn && (
              <div className="flex justify-center">
                <SignInButton />
              </div>
            )}
            {isSignedIn && <CreatePostWizard />}
          </div>

          <div>
            {data?.map((post) => (
              <div key={post.id} className="border-b p-8">
                {post.content}
              </div>
            ))}
          </div>
        </div>
      </main>
    </>
  );
}
